### PR TITLE
only include artifacts of type jar (source and javadoc are unnecessary)

### PR DESCRIPTION
**Pull request by enijns**
see https://github.com/xerial/sbt-pack/issues/62

### CODE REVIEW

**Comment by xerial** [comment]
Travis build has failed. Retrying now.

**Comment by xerial** [comment]
@enijns 
Tests still failing. The error shows missing snappy-java-1.1.1.6.jar, whose artifact type is 'bundle', not the jar.  
https://travis-ci.org/xerial/sbt-pack/builds/54564557#L1157

**Comment by enijns** [comment]
@xerial 
OK. It's probably safer to only exclude the artifacts with type 'sources' and 'javadoc' instead of figuring out the exhaustive list of artifact types that belong in the package.

**Comment by enijns** [comment]
I'll try to update the pull request. 
Unfortunately the scripted tests don't seem to like our corporate proxy and I have no clue how to fix this, so I can't run the tests before I send the update your way.

**Comment by xerial** [comment]
In this case, let TravisCI test your project.  Or set proxy: http://stackoverflow.com/questions/13803459/how-to-use-sbt-from-behind-proxy

**Comment by xerial** [comment]
Looks good. Thanks for the fix.

**Comment by NicolasRouquette** [comment]
FYI: the default exclusions don't seem to be effective (with SBT 0.13.8):

    packExcludeArtifactTypes := Seq("source", "javadoc", "test")

Instead, the following works for me:

    packExcludeArtifactTypes := Seq("src", "doc", "test")

**Comment by enijns** [comment]
@NicolasRouquette I didn't think very hard about the default exclusions - they surely can be improved upon (I can't use the defaults myself so don't really care either way). I'm not sure what the default artifact type strings should be though.

**Pull request merged**
